export const customer = {
  SET_COLLECTION: 'CUSTOMER.SET_COLLECTION',
  FETCH_COLLECTION: 'CUSTOMER.FETCH_COLLECTION',
  ADD_TO_COLLECTION: 'CUSTOMER.ADD_TO_COLLECTION'
}

export const error = {
  EXTERNAL: 'ERROR.EXTERNAL'
}